<template>
	<PolygonjsScene
		:loadFunction="loadFunction"
		:sceneName="'Jokuh_Web'"
		@sceneready="onSceneReady"
	/>
</template>

<script lang="ts">
import { defineComponent, ref, watch, computed } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { loadScene_jokuh_web } from "./jokuh_web/autogenerated/loadScene";
import type { PolySceneWithNodeMap_jokuh_web } from "./jokuh_web/autogenerated/PolySceneWithNodeMap";


export default defineComponent({
	name: "scene-01",
	components: {
		PolygonjsScene,
	},
	setup() {
		let scene: PolySceneWithNodeMap_jokuh_web | undefined;

		function onSceneReady(loadedScene: PolySceneWithNodeMap_jokuh_web) {
			scene = loadedScene;
		}
		const loadFunction = computed(() => loadScene_jokuh_web);

		return {
			loadFunction,
			onSceneReady,
		};
	},
});
</script>

<style></style>
